// Bundles with esbuild. Declarations are emitted afterwards by `tsc -p tsconfig.build.json`.
// src/schema.d.ts (generated by openapi-typescript) is a declaration file, so tsc does not emit it:
// it is copied verbatim so that dist/index.d.ts can import it.
import { build } from 'esbuild';
import { rmSync, readFileSync, mkdirSync, copyFileSync } from 'node:fs';

const pkg = JSON.parse(readFileSync(new URL('../package.json', import.meta.url), 'utf8'));
const banner = `/*! ${pkg.name} v${pkg.version} | MIT | (c) TKAWEN */`;
const common = {
  bundle: true,
  target: 'es2020',
  legalComments: 'none',
  banner: { js: banner },
  logLevel: 'info',
};

rmSync(new URL('../dist', import.meta.url), { recursive: true, force: true });

await Promise.all([
  build({ ...common, entryPoints: ['src/index.ts'], outfile: 'dist/index.js', format: 'esm', platform: 'neutral' }),
  build({ ...common, entryPoints: ['src/index.ts'], outfile: 'dist/index.cjs', format: 'cjs', platform: 'node' }),
]);

mkdirSync(new URL('../dist', import.meta.url), { recursive: true });
copyFileSync(new URL('../src/schema.d.ts', import.meta.url), new URL('../dist/schema.d.ts', import.meta.url));
